---
- name: Install prometheus
  hosts: webservers
  become: true
  become_method: sudo

  tasks:
       - name: Download prometheus using get_url
         get_url:
               url:  https://github.com/prometheus/prometheus/releases/download/v2.27.1/prometheus-2.27.1.linux-amd64.tar.gz
               dest: /home/ubuntu

       - name: Install Prometheus to home for Slave
         unarchive:
                 src : /home/ubuntu/prometheus-2.27.1.linux-amd64.tar.gz
                 dest: /home/ubuntu/prometheus